### ISSUE TITLE
Remove mandatory to have a auto-increment @PrimaryKey field on the referenced entity

### ISSUE THREAD

**Issue by almozavr** [ahmetb/orman#28]
I found orman very simple to understand and easy to maintain. It's usage is really awesome. But because of restriction to use auto-increment field I can't use it in my project and that's way:
1. I have many entities with fields of ref. entities
2. Many of ref. entities have the "id" field which I get from server (btw it's a client-server app, some kind of advanced messenger)
3. Mandatory to have auto-increment field disallows creating primary keys for my "id" fields. 
4. So dozens of duplicates :(
5. As I use it for Android, db size and performance means a lot.

I appreciate your work (framework is really cool comparing to db4o, ormlite etc.) and hope one day my issue would be accepted. Thanks.

**Comment by ahmetb** [comment]
Thanks for your feedback. Actually as we say in wiki, orman is not created aiming advanced apps at all e.g. requires custom PK. The reason that we force a single PK is, it makes much easier to do reverse binding, x-to-x mappings because everything is under framework's control. Once I tried to remove that constraint and that required serious changes in architecture. 

This is an approach that makes the usage easier and also clear for dummies which very famous frameworks (e.g. Play framework) also use.

One solution can be you can leave your `id` field (that comes from server) as a non-PK field and let orman create `@PrimaryKey(autoIncrement=true)` on a dummy field. e.g. `_id`. I don't see the point it creates duplicates here (maybe it is specific to your app?)

If you want a column to be unique, you can use the annotation `@Index(unique = true)` if you want that column to have a unique index (which can replace PK in your case).  Does this solve your case?

**Comment by almozavr** [comment]
Thanks for a very quick answer, I'm still trying to go further. So

> let orman create @PrimaryKey(autoIncrement=true) on a dummy field.

Surely, that's what I do

> @Index(unique = true)

Sorry, didn't find it in wiki.

> Does this solve your case?

I'm still in a trouble. And I don't believe there is nothing to do, 'cause it would be a pity to map my objects and scheme into crappy Android SQLite by hands :(
I just wonder how ORMan works and can't say @Index(unique = true) really helps, 'cause now I got many exceptions to solve (if they are solvable in my situation). Thanks again!

**Comment by ahmetb** [comment]
Sorry about undocumenting it. :) Actually the framework has more features than we have documented. Our idea of framework is good but I'm not sure about how is our implementation and reliability of framework since we use it only for our small projects. Let us know if you hit similar stuff again.

**Comment by kylba4enko** [comment]
Hello. Your framework really cool! But I have the same problem with auto increment field (id). And because of it I can't use it in my app. I need a primary key but I do not need auto increment this field. How can I solve this if it is possible?
