### ISSUE TITLE
Android - MappingSessionAlreadyStartedException

### ISSUE THREAD

**Issue by ragunathjawahar** [ahmetb/orman#39]
I start the Mapping Session in my Activity's **onCreate** method. Once I back out of the application and restart it once again I get the following exception:

```
11-27 17:55:53.448: E/AndroidRuntime(754): Caused by: org.orman.mapper.exception.MappingSessionAlreadyStartedException: Mapping session has already been started. Do not use start method more than once.
```

The app then crashes, but the next time I open the app, it works fine.

``` Java
public static void initOrmanMappingSession(Class<?>[] entityClasses,  Database database) {
        System.gc();

        MappingSession.getConfiguration().setCreationPolicy(SchemaCreationPolicy.CREATE_IF_NOT_EXISTS);
        MappingSession.registerDatabase(database);
        for(Class<?> clazz : entityClasses) {
            MappingSession.registerEntity(clazz);
        }

        MappingSession.startSafe();
}
```

**Comment by ahmetb** [comment]
Well, you are using `startSafe` method which is okay, however somehow this `initOrmanMappingSession` method is called twice, I think.

Therefore it tries to register entity classes after the session is statically started. That causes the exception. I thought that I have created a public method called `isSessionStarted()` but clearly I was wrong. There's a `sessionStarted` variable in [`MappingSession.java`](https://github.com/ahmetalpbalkan/orman/blob/master/src/org/orman/mapper/MappingSession.java) and it is private at this moment.

The only way to make it work before I fix this is just put a huge try...catch around this code which catches the `MappingSessionAlreadyStartedException` and immediately quits. I think this is safe. As I stated before, this happens because your method is created twice. I also have encountered this issue in Android, probably it is because static scope is not hundred percent cleaned up by garbage collector after relaunching the app in a short time. Thanks for noticing this issue.

-- ahmet alp balkan

**Comment by ragunathjawahar** [comment]
@ahmetalpbalkan, I chose to use <code>MappingSession.startSafe()</code> after looking into the source code. Therefore  if I would have called the <code>initOrmanMappingSession</code> twice, the method should actually return. Which is not the case here, I have called <code>initOrmanMappingSession</code> method only once in my code.

And out of curiosity, why isn't there a <code>MappingSession.end()</code> to clean up the resources? I just close the database using the <code>database.closeConnection()</code> when the activity is destroyed. Do you have any best practices that you can recommend?

**Comment by ahmetb** [comment]
You are right. If your code would reach `startSafe()` twice, it would return immediately on second call. The problem is, before calling startSafe twice,you are `MappingSession.registerEntity(clazz);` registering entities twice which causes exception. This exception can be ignored using try..catch as I said before

There is not so much need for an `end()` method. Basically everything ORMAN initialized are just pure java classes and will be collected out by garbage collector soon. The best practise is to use `db.closeConnection()` which clearly states what it does. Is that what you asked about? Thanks.

**Comment by ragunathjawahar** [comment]
What's your take on the following use cases?

1) How would you handle the mapping session when the db access is needed across several activities?
2) When would you close the database connection across several activities?
3) I suggest a Singelton pattern would be better instead of using static fields and methods. What do you suggest?

**Comment by ahmetb** [comment]
(1)(3) Singleton will just work. However remember that the whole mapping session is static. If you just create a singleton to provide MappingSession, it will work, but if you access MappingSession from several activities, that'll also work since everything is static at that moment. That's my guess. I haven't tried it on advanced Android projects but some people did and they made it work.

(2) it is the same behavior as calling `close()` method on `import android.database.sqlite.SQLiteDatabase;`. Its behavior is not clearly defined in [documentation](http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#close%28%29) however I think calling it twice or more will just work fine. Besides that, in your singleton you can keep a boolean and serve `close()` method so that you can make sure that `close()` is called only once if different activities call it.

My recommendation is, if you are using database across several entities, do not close the database. It will automatically collected by gc, therefore connection to the database (there's only one) will be disposed. It is quite safe not to use close() method in multiple-activity case since other activities may need to use DB after one of them closes connection to DB. I hope that makes more sense now.

I uploaded a new build to Downloads section. Now you can use 

```
if(!MappingSession.isSessionStarted(){
    initOrmanMappingSession(); 
}
```

  safely.

**Comment by ragunathjawahar** [comment]
This works if I didn't call <code>database.closeConnection()</code> but causes a memory leak in the application. Here is the stack trace for your reference.

```
close() was never explicitly called on database '/data/data/my.package.name/databases/database.sqlite' 
android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
    at android.database.sqlite.SQLiteDatabase.<init>(SQLiteDatabase.java:1810)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:817)
    at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:851)
    at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:844)
    at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:540)
    at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:203)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:98)
    at org.orman.dbms.sqliteandroid.SQLiteAndroid.<init>(SQLiteAndroid.java:39)
    at my.package.name.BucketListActivity.onCreate(BucketListActivity.java:55)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
    at android.app.ActivityThread.access$2300(ActivityThread.java:125)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:4627)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ahmetb** [comment]
If you trust your code so that it won't try to access a terminated database connection, then just use close() somewhere appropriate, for example [onDestroy()](http://developer.android.com/reference/android/app/Activity.html#ActivityLifecycle) method.

**Comment by ragunathjawahar** [comment]
Instead I've started the <code>MappingSession</code> on the <code>onCreate()</code> method of the <code>Application</code> instance. This seems to be the best solution for the current design.

**Comment by ahmetb** [comment]
Thanks for pointing this out. I didn't even use to know there's an Application class specific for the app. Could you please show me a link or consider contributing our wiki on Android section?

**Comment by ragunathjawahar** [comment]
@ahmetalpbalkan, you're welcome, I also updated the wiki.

**Comment by rudreshsp** [comment]
@ahmetalpbalkan,@ragunathjawahar 

can you show me the link to that wiki, i have been using orman for last 4 years,in all my projects, now life is misserable b'cos of this bad decission, database leak issue is the main problem form me,as i m using inside services, suppose if i closeconnection after my operation, then tries to open it again it give the following "trying to open an already closed on error" so where to start and where to close , im frustrated, also there is no method check isOpen as in case of SQLiteDatabase in our  org.orman.dbms.Database..?? pls help me sirs....

rudresh.soft@gmail.com

**Comment by ragunathjawahar** [comment]
@rudreshsp Orman is no longer maintained. You have to switch to other alternatives.
