### ISSUE TITLE
How to connect two db at the same time

### ISSUE THREAD

**Issue by jachicore** [ahmetb/orman#55]
How to connect two db at the same time? 
        MappingSession.registerPackage("xxxx");
        MappingSession.registerDatabase(db);
        MappingSession.start();
It's same like that it can only init one db connection and entity the db mapping.So if I want to connect two db at the same time,How can I do?

**Comment by ahmetb** [comment]
@jachicore unfortunately by design it works with only one db at a time because many things are static in this library. I wasn't a good software engineer enough back in my sophomore year at college. :trollface: I would certainly not design it like this today.

Here's a selfie to hopefully tease this problem:
![selfie-0](http://i.imgur.com/sRJDtSl.png)

**Comment by jachicore** [comment]
Haha...So handsome.
